name: Model CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'models/**'
      - 'tests/**'
      - '.github/workflows/model-ci-cd.yml'

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install -r requirements.txt

    - name: Run Model Tests
      id: model_tests
      run: |
        pytest tests/

    - name: Upload Model Artifact
      if: success()  # This ensures it runs only if previous step succeeded
      uses: actions/upload-artifact@v4
      with:
        name: iris-model
        path: models/iris_model.pkl

    - name: Upload deepcheck report to GitHub Artifact
      uses: actions/upload-artifact@v4
      with:
        name: deepcheck-report
        path: tests/deepchecks_report.html        

    - name: Start FastAPI App (CD)
      if: success()  # Conditional CD: only run if CI steps passed
      run: |
        cd app
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
